v18.0
turnkeylinux-apps/foodsoft pull request #11
Opened 2023-10-06 15:00 UTC by qq7

2023-12-06 00:46 UTC, OnGle approved these changes
lgtm

2023-12-09 00:02 UTC, Christie018 requested changes
I've reviewed the code changes and requested changes.

2023-12-09 00:02 UTC, Christie018 commented on Makefile
>  WEBMIN_FW_TCP_INCOMING = 22 80 443 12320 12321
I believe port 12320 can be removed for non-existent web shell.

2024-04-17 03:10 UTC, Christie018 commented
LGTM!

2024-08-30 04:15 UTC, JedMeister commented
Closed as per https://github.com/turnkeylinux/tracker/issues/1982

2024-08-30 04:15 UTC, closed without merging